---
--- Generated by Luanalysis
--- Created by depers.
--- DateTime: 2021/11/3 21:21
---

-- 获取方法的签名特征
local methodKey = KEYS[1]
redis.log(redis.LOG_DEBUG, 'key is ', methodKey)

-- 调用脚本传入的限流大小
local limit = tonumber(ARGV[1])

-- 获取当前流量大小
local count = tonumber(redis.call('get', methodKey) or "0")

-- 是否超出限流阀值
if  count + 1 > limit then
    -- 拒绝服务访问
    return false
else
    -- 没有超过阀值，设置当前访问的数量 +1
    redis.call("INCRBY", methodKey, 1)
    -- 设置过期时间
    redis.call("EXPIRE", methodKey, 1)
    -- 放行
    return true
end